Repository Monorama-IoT-Platform/IoT-Server, pull requests merged in 2025-05, with the labels that each got.

#4 :sparkles: Feat: 보일러플레이트 구성
  build.gradle
  gradle.properties
  src/main/java/com/monorama/iot_server/annotation/Date.java
  src/main/java/com/monorama/iot_server/annotation/LocalDateValidator.java
  src/main/java/com/monorama/iot_server/annotation/UserId.java
  src/main/java/com/monorama/iot_server/config/WebMvcConfig.java
  src/main/java/com/monorama/iot_server/constant/Constant.java
  src/main/java/com/monorama/iot_server/controller/.gitkeep
  src/main/java/com/monorama/iot_server/dto/ExceptionDto.java
  src/main/java/com/monorama/iot_server/dto/JwtTokenDto.java
  src/main/java/com/monorama/iot_server/dto/ResponseDto.java
  src/main/java/com/monorama/iot_server/dto/SelfValidating.java
  src/main/java/com/monorama/iot_server/dto/request/.gitkeep
  src/main/java/com/monorama/iot_server/dto/response/.gitkeep
  src/main/java/com/monorama/iot_server/exception/CommonException.java
  src/main/java/com/monorama/iot_server/exception/ErrorCode.java
  src/main/java/com/monorama/iot_server/exception/GlobalExceptionHandler.java
  src/main/java/com/monorama/iot_server/interceptor/ResponseInterceptor.java
  src/main/java/com/monorama/iot_server/interceptor/UserIdInterceptor.java
  src/main/java/com/monorama/iot_server/interceptor/UserIdResolver.java
  src/main/java/com/monorama/iot_server/repository/.gitkeep
  src/main/java/com/monorama/iot_server/service/.gitkeep
  src/main/java/com/monorama/iot_server/type/EProvider.java
  src/main/java/com/monorama/iot_server/type/EProviderFactory.java
  src/main/java/com/monorama/iot_server/type/ERole.java
  src/main/java/com/monorama/iot_server/util/CookieUtil.java
  src/main/java/com/monorama/iot_server/util/HeaderUtil.java
Labels: feature

#9 ✨ Feat: 헬스데이터 회원가입 약관 조회 API 구현
  build.gradle
  src/main/java/com/monorama/iot_server/controller/HealthData/HealthTermsController.java
  src/main/java/com/monorama/iot_server/domain/Terms.java
  src/main/java/com/monorama/iot_server/domain/type/ServiceType.java
  src/main/java/com/monorama/iot_server/domain/type/TermsType.java
  src/main/java/com/monorama/iot_server/dto/response/terms/TermsListResponseDto.java
  src/main/java/com/monorama/iot_server/dto/response/terms/TermsResponseDto.java
  src/main/java/com/monorama/iot_server/repository/TermsRepository.java
  src/main/java/com/monorama/iot_server/service/TermsService.java
Labels: feature

#11 :pencil2: Fix: 도메인 어노테이션 오류 및 잘못된 초기화 로직 수정
  src/main/java/com/monorama/iot_server/domain/AirMetaData.java
  src/main/java/com/monorama/iot_server/domain/AirMetaDataItem.java
  src/main/java/com/monorama/iot_server/domain/AirQualityData.java
  src/main/java/com/monorama/iot_server/domain/HealthData.java
  src/main/java/com/monorama/iot_server/domain/Project.java
  src/main/java/com/monorama/iot_server/domain/User.java
  src/main/java/com/monorama/iot_server/domain/UserDataPermission.java
  src/main/java/com/monorama/iot_server/domain/UserProject.java
Labels: bug, enhancement

#12 :sparkles: Feat: 구글 소셜 로그인 기능 추가
  src/main/java/com/monorama/iot_server/config/SecurityConfig.java
  src/main/java/com/monorama/iot_server/constant/Constant.java
  src/main/java/com/monorama/iot_server/controller/.gitkeep
  src/main/java/com/monorama/iot_server/controller/AuthController.java
  src/main/java/com/monorama/iot_server/domain/embedded/PersonalInfoItem.java
  src/main/java/com/monorama/iot_server/dto/request/.gitkeep
  src/main/java/com/monorama/iot_server/dto/request/PMRegisterDto.java
  src/main/java/com/monorama/iot_server/repository/.gitkeep
  src/main/java/com/monorama/iot_server/repository/UserRepository.java
  src/main/java/com/monorama/iot_server/security/AbstractAuthenticationFailure.java
  src/main/java/com/monorama/iot_server/security/JwtAuthEntryPoint.java
  src/main/java/com/monorama/iot_server/security/JwtAuthenticationProvider.java
  src/main/java/com/monorama/iot_server/security/JwtAuthenticationToken.java
  src/main/java/com/monorama/iot_server/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/monorama/iot_server/security/filter/JwtExceptionFilter.java
  src/main/java/com/monorama/iot_server/security/handler/CustomLogOutProcessHandler.java
  src/main/java/com/monorama/iot_server/security/handler/CustomLogOutResultHandler.java
  src/main/java/com/monorama/iot_server/security/handler/DefaultFaiureHandler.java
  src/main/java/com/monorama/iot_server/security/handler/DefaultSuccessHandler.java
  src/main/java/com/monorama/iot_server/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/monorama/iot_server/security/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/monorama/iot_server/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/monorama/iot_server/security/info/GoogleOAuth2UserInfo.java
  src/main/java/com/monorama/iot_server/security/info/JwtUserInfo.java
  src/main/java/com/monorama/iot_server/security/info/OAuth2UserInfo.java
  src/main/java/com/monorama/iot_server/security/info/OAuth2UserInfoFactory.java
  src/main/java/com/monorama/iot_server/security/info/UserPrincipal.java
  src/main/java/com/monorama/iot_server/security/service/CustomOAuth2UserService.java
  src/main/java/com/monorama/iot_server/security/service/CustomUserDetailService.java
  src/main/java/com/monorama/iot_server/service/.gitkeep
  src/main/java/com/monorama/iot_server/service/AuthService.java
  src/main/java/com/monorama/iot_server/type/EProvider.java
  src/main/java/com/monorama/iot_server/type/EProviderFactory.java
  src/main/java/com/monorama/iot_server/type/ERole.java
  src/main/java/com/monorama/iot_server/util/JwtUtil.java
Labels: feature

#15 Feature/공기질앱 공기질 데이터 저장
  src/main/java/com/monorama/iot_server/controller/AirQuality/AirQualityDataController.java
  src/main/java/com/monorama/iot_server/domain/AirQualityData.java
  src/main/java/com/monorama/iot_server/domain/embedded/AirQualityDataItem.java
  src/main/java/com/monorama/iot_server/dto/request/AirQuality/AirQualityDataRequestDto.java
  src/main/java/com/monorama/iot_server/repository/AirQualityDataRepository.java
  src/main/java/com/monorama/iot_server/service/AirQualityDataService.java
Labels: feature

#22 :sparkles: Feat: 헬스 데이터 실시간 및 동기화 전송 기능 추가
  src/main/java/com/monorama/iot_server/controller/healthdata/HealthDataController.java
  src/main/java/com/monorama/iot_server/controller/healthdata/HealthDataProjectController.java
  src/main/java/com/monorama/iot_server/controller/healthdata/HealthDataProjectTermsController.java
  src/main/java/com/monorama/iot_server/controller/healthdata/HealthDataSignUpTermsController.java
  src/main/java/com/monorama/iot_server/domain/HealthData.java
  src/main/java/com/monorama/iot_server/domain/embedded/HealthDataItem.java
  src/main/java/com/monorama/iot_server/dto/request/HealthDataRequestDto.java
  src/main/java/com/monorama/iot_server/dto/request/HealthDataSyncRequestDto.java
  src/main/java/com/monorama/iot_server/repository/HealthDataRepository.java
  src/main/java/com/monorama/iot_server/service/healthdata/HealthDataProjectService.java
  src/main/java/com/monorama/iot_server/service/healthdata/HealthDataService.java
Labels: feature

#23 :sparkles: Feat: 공기질 프로젝트 관련 기능 구현
  src/main/java/com/monorama/iot_server/controller/airquality/AQDController.java
  src/main/java/com/monorama/iot_server/controller/airquality/AQDProjectController.java
  src/main/java/com/monorama/iot_server/controller/airquality/AQDProjectTermsController.java
  src/main/java/com/monorama/iot_server/domain/AirQualityData.java
  src/main/java/com/monorama/iot_server/domain/embedded/AirQualityDataItem.java
  src/main/java/com/monorama/iot_server/dto/request/airquality/AQDRealtimeRequestDto.java
  src/main/java/com/monorama/iot_server/dto/response/project/ProjectDetailResponseDto.java
  src/main/java/com/monorama/iot_server/exception/GlobalExceptionHandler.java
  src/main/java/com/monorama/iot_server/repository/AQDProjectRepository.java
  src/main/java/com/monorama/iot_server/repository/AQDRepository.java
  src/main/java/com/monorama/iot_server/service/AirQualityDataService.java
  src/main/java/com/monorama/iot_server/service/airquality/AQDProjectService.java
  src/main/java/com/monorama/iot_server/service/airquality/AQDService.java
Labels: feature

#25 ✨ Feat: 회원가입 기능 구현 및 필드 초기화 문제 해결
  src/main/java/com/monorama/iot_server/annotation/PhoneNumber.java
  src/main/java/com/monorama/iot_server/annotation/PhoneNumberValidator.java
  src/main/java/com/monorama/iot_server/config/SecurityConfig.java
  src/main/java/com/monorama/iot_server/constant/Constant.java
  src/main/java/com/monorama/iot_server/controller/AuthController.java
  src/main/java/com/monorama/iot_server/domain/User.java
  src/main/java/com/monorama/iot_server/domain/UserDataPermission.java
  src/main/java/com/monorama/iot_server/domain/embedded/AirQualityDataFlag.java
  src/main/java/com/monorama/iot_server/domain/embedded/HealthDataFlag.java
  src/main/java/com/monorama/iot_server/domain/embedded/PersonalInfoFlag.java
  src/main/java/com/monorama/iot_server/domain/type/LoginProvider.java
  src/main/java/com/monorama/iot_server/domain/type/Role.java
  src/main/java/com/monorama/iot_server/dto/request/register/PMRegisterDto.java
  src/main/java/com/monorama/iot_server/dto/request/register/UserRegisterDto.java
  src/main/java/com/monorama/iot_server/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/monorama/iot_server/service/AuthService.java
  src/main/java/com/monorama/iot_server/type/ERole.java
Labels: bug, enhancement, feature

#29 ✨ Feat: metadata 저장, 항목 조회, 항목 및 데이터 조회 구현
  src/main/java/com/monorama/iot_server/controller/metadata/MetaDataController.java
  src/main/java/com/monorama/iot_server/domain/AirMetaData.java
  src/main/java/com/monorama/iot_server/domain/AirMetaDataItem.java
  src/main/java/com/monorama/iot_server/dto/request/metadata/MetaDataListRequestDto.java
  src/main/java/com/monorama/iot_server/dto/request/metadata/MetaDataRequestDto.java
  src/main/java/com/monorama/iot_server/dto/request/pm/ProjectRequestDto.java
  src/main/java/com/monorama/iot_server/dto/response/metadata/MetaDataItemListResponseDto.java
  src/main/java/com/monorama/iot_server/dto/response/metadata/MetaDataItemResponseDto.java
  src/main/java/com/monorama/iot_server/dto/response/metadata/MetaDataListResponseDto.java
  src/main/java/com/monorama/iot_server/dto/response/metadata/MetaDataResponseDto.java
  src/main/java/com/monorama/iot_server/exception/ErrorCode.java
  src/main/java/com/monorama/iot_server/exception/GlobalExceptionHandler.java
  src/main/java/com/monorama/iot_server/repository/AirMetaDataItemRepository.java
  src/main/java/com/monorama/iot_server/repository/AirMetaDataRepository.java
  src/main/java/com/monorama/iot_server/repository/UserDataPermissionRepository.java
  src/main/java/com/monorama/iot_server/security/JwtAuthEntryPoint.java
  src/main/java/com/monorama/iot_server/security/converter/CustomRequestEntityConverter.java
  src/main/java/com/monorama/iot_server/security/handler/DefaultFailureHandler.java
  src/main/java/com/monorama/iot_server/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/monorama/iot_server/security/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/monorama/iot_server/security/service/CustomOAuth2UserService.java
  src/main/java/com/monorama/iot_server/service/AuthService.java
  src/main/java/com/monorama/iot_server/service/metadata/MetaDataService.java
Labels: feature

#31 :sparkles: Feat: 토큰 재발급 API 및 쿠키 설정 로직 추가
  src/main/java/com/monorama/iot_server/constant/Constant.java
  src/main/java/com/monorama/iot_server/controller/AuthController.java
  src/main/java/com/monorama/iot_server/repository/UserRepository.java
  src/main/java/com/monorama/iot_server/service/AuthService.java
  src/main/java/com/monorama/iot_server/util/CookieUtil.java
  src/main/java/com/monorama/iot_server/util/JwtUtil.java
Labels: feature

#35 ✨ Feat: 사용자 권한 정보 스케줄러
  .gitignore
  src/main/java/com/monorama/iot_server/config/SchedulerConfig.java
  src/main/java/com/monorama/iot_server/config/SecurityConfig.java
  src/main/java/com/monorama/iot_server/repository/UserProjectRepository.java
  src/main/java/com/monorama/iot_server/service/PermissionUpdateService.java
Labels: enhancement, feature

#36 :sparkles: Feat: CORS 설정 및 인증 로직 설정값 외부화 리팩토링
  src/main/java/com/monorama/iot_server/config/CorsConfig.java
  src/main/java/com/monorama/iot_server/config/SecurityConfig.java
  src/main/java/com/monorama/iot_server/controller/AuthController.java
  src/main/java/com/monorama/iot_server/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/monorama/iot_server/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/monorama/iot_server/util/CookieUtil.java
  src/main/java/com/monorama/iot_server/util/JwtUtil.java
Labels: enhancement, feature

#45 ✨ Feat: ProjectDetail 응답 스키마 확장 및 약관 필드 추가함
  src/main/java/com/monorama/iot_server/controller/AuthController.java
  src/main/java/com/monorama/iot_server/domain/User.java
  src/main/java/com/monorama/iot_server/dto/response/project/AirMetaDataItemResponseDto.java
  src/main/java/com/monorama/iot_server/dto/response/project/ProjectDetailResponseDto.java
  src/main/java/com/monorama/iot_server/dto/response/project/ProjectSimpleResponseDto.java
  src/main/java/com/monorama/iot_server/service/AuthService.java
  src/main/java/com/monorama/iot_server/service/airquality/AQDProjectService.java
  src/main/java/com/monorama/iot_server/service/healthdata/HDProjectService.java
  src/main/java/com/monorama/iot_server/service/pm/PMService.java
Labels: enhancement, feature
